include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 80

linter:
  rules:
    - always_put_required_named_parameters_first
    - avoid_final_parameters
    - avoid_multiple_declarations_per_line
    - cascade_invocations
    - flutter_style_todos
    - prefer_asserts_with_message
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_single_quotes
    - prefer_spread_collections
    - sort_constructors_first
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - use_string_buffers

analyzer:
  errors:
    todo: ignore
