targets:
  $default:
    builders:
      json_serializable:
        options:
          checked: true
          explicit_to_json: true
          field_rename: snake
          include_if_null: false
        generate_for:
          - "**/*_model.dart"
