name: flutter_apps

packages:
  - apps/**
  - packages/**

scripts:
  analyze:
    exec: dart analyze .
  build_runner:
    exec: dart run build_runner build --delete-conflicting-outputs

  clean_gen:
    exec: dart run build_runner clean
