name: flit_notes
description: "Flit notes app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  meta: ^1.16.0
  flutter_native_splash: ^2.4.4

  # Dependency injection
  get_it: ^8.0.3
  injectable: ^2.5.0

  # Routing
  auto_route: ^9.3.0+1

  # Data layer
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  flutter_secure_storage: ^9.2.4
  flutter_dotenv: ^5.2.1

  # Presentation layer
  google_fonts: ^6.2.1

  # Helpers
  json_annotation: ^4.9.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_flavorizr: ^2.2.3

  # Generators
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.4
  auto_route_generator: ^9.3.1

  # Testing
  test: ^1.25.15
  bloc_test: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - env/
    - assets/
    - assets/branding/
